version: '3'

services:
    nginx:
        image: nginx
        volumes: 
            - ./nginx:/usr/share/ngnix/html
        ports: 
            - 8080:80

    redis:
        image: redis:alpine
        expose: 
            - 6379